* About this repository

This repository contains different configuration files, which I have been
writing since 2005.

* Contents:
- =cmd/= — shell-related configuration files.
- =utils/= — configuration files for different utilities, like vim or tmux.
- =noauto/= — different system configuration files, not for automatic
  installation. Described below.
- =deploy.sh= — main deployment script.

** =noauto/= contents:
- =hosts= — =/etc/hosts= file. This is not a valid =hosts= file! You should
  review it and add useful entries to your =/etc/hosts= by hands!
- =50trackball.conf= — X configuration for Logitech trackball
- =50-udiskie.rules= — Rules for udiskie. Should be placed in
  =/etc/polkit-1/rules.d/=. Owner should be =polkitd=, and access right should be
  =644=.
- =97-udisks2.rules= — Rules for udiskie [2]. Should be placed in
  =/etc/udev/rules.d/=.

* Dependencies:
You should have next programs in system before configuration deployment:

** System programs:
- aspell (with aspell-ru dictionary)
- bc
- cal
- cron
- cpupower
- curl
- make (or gmake executable should be available in FreeBSD)
- python3
- perl
- rsync
- sqlite3
- stow
- syncthing
- sudo
- tmux (>= 3.2)
- xsltproc
- udisks
- zsh

** Mail and IM:
- abook
- fdm
- lynx
- maildrop
- msmtp
- mutt
- [[https://github.com/rss2email/rss2email][rss2email]]
- urlview

** Editing:
- buttercup (for compiling gnuplot-mode for Emacs)
- ctags
- diff-highlight (can be installed with `pip3 install diff-highlight`)
- emacs
- gnuplot
- idea
- lacheck
- latex (texlive)
- vim

** Utilities:
- ansiweather
- dunst
- git
- gpg
- hledger
- jq
- mc
- numlockx
- pass
- pass-otp
- rtorrent
- shred
- wget
- xclip
- yt-dlp
- udiskie

** Multimedia:
- feh
- gimp
- imagemagick
- lame
- mplayer
- rawtherapee
- shotcut
- sxiv

** GUI:
- audacious
- firefox
- i3
- josm
- qmapshack
- telegram
*** Fonts:
- Terminus
- Noto Mono

** Additional packages for Termux:
- termux-api

* Before deployment:
If you need sensitive data (passwords, API keys, etc) in the new machine — use
=store_sensitive_data.sh= script to save it in archive on the old machine and
move to the new machine.

On the new machine you should do the next, to import sensitive data:
** File synchronization:
To work with file synchronization via cloudsync you need to have =sync=
SSH-key with empty passphrase. This key should be added to remote server to
=rsync= account into =~/.ssh/authorized_keys=.

** Passwords:
For using Mutt with GMail mailboxes you should specify mail server passwords
in =~/.netrc=.

** Import GPG keys:
Use this commands:
#+BEGIN_EXAMPLE
gpg --import pub.key
gpg --import priv.key
#+END_EXAMPLE

After that call =gpg --edit-key <key-id>= and set trust level to 5 via command
=trust=. Quit gpg console with =quit= command.

** Weather forecasts:
Add your OpenWeatherMap API key to =~/.openweathermap= file.

* Deployment:
1. Clone this repository to some suitable directory. You *mustn't* clone it to
   your =~= directory!
2. Run =deploy.sh= script, which do the next:
   1) Make soft links from our catalog to the user $HOME catalog via stow.
   2) Create necessary empty directories.
   3) Create mail directories.
   4) Set right access rights to some configuration files.
   5) Store in =~= special file with OS and hardware type of machine where
      this repository is cloned to. It is necessary to properly handle some
      functions, which should exists on one machine and shouldn't on another.

* After deployment:
** Vim plugins installation
Do the next to install Vim plugins:
- First, install Vundle plugin: =git clone
  https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim=.
- Second, in Vim execute =:BundleInstall=.

** Emacs plugins compilation:
Run =C-u 0 M-x byte-recompile-directory= to recomplile contents of
=~/.emacs.d/plugins=.
*** Org-mode installation:
Sometimes Org-mode will not install via =use-package= plugin.

To install Org-mode enter =M-x list-packages= and find =org= in opened
buffer. Then press =i= on org entry and =x= to install it.
*** Pinentry installation:
=M-x package-install= -> =pinentry= — if it is not installed itself via
=use-package=.

** /etc/hosts:
You should update your =/etc/hosts= with data from =noauto/hosts=.

** sudo setup:
If you need to control brightness of display when starting X-server — add next
line to =/etc/sudoers=:
#+BEGIN_EXAMPLE
drag0n ALL=(root) NOPASSWD: /usr/bin/tee /sys/class/backlight/intel_backlight/brightness
#+END_EXAMPLE

To use dunst, not xfce4-notifyd in i3wm session — add next line to =/etc/sudoers=:
#+BEGIN_EXAMPLE
drag0n ALL=(root) NOPASSWD: /usr/bin/pkill xfce4-notifyd
#+END_EXAMPLE

To setup cpu frequency on Thinkpad, add this:
#+BEGIN_EXAMPLE
drag0n ALL=(root) NOPASSWD: /usr/bin/cpupower
#+END_EXAMPLE
