#!/bin/sh

# Slackware Linux VNC session startup script
#
unset SESSION_MANAGER
#exec /etc/X11/xinit/xinitrc
exec /home/drag0n/.xinitrc

# Another example of setting up desktop environment
#
# [ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
# [ -r /.Xresources ] && xrdb /.Xresources
# xsetroot -solid grey
# vncconfig -iconic &
# xterm -geometry 80x24+10+10 -ls -title " Desktop" &
# twm &
