(setq-default ispell-program-name "aspell")
(setq ispell-list-command "list")
(setq ispell-extra-args '("--sug-mode=ultra"))

(global-set-key [f12] (lambda ()
                        (interactive)
                        (setq ispell-local-dictionary "ru")
                        (setq flyspell-dictionary "ru")
                        (flyspell-mode)))
(global-set-key [f11] (lambda ()
                        (interactive)
                        (setq ispell-local-dictionary "en")
                        (setq flyspell-dictionary "en")
                        (flyspell-mode)))
