(use-package cheatsheet
  :pin melpa
  :commands (cheatsheet-show)
  :config
  (cheatsheet-add-group 'Emacs
                        '(:key "C-z" :description "Switch keyboard language")
                        '(:key "M-g" :description "Go to line")
                        '(:key "C-j" :description "Insert new line below cursor")
                        '(:key "C-x 2" :description "Horizontal split")
                        '(:key "C-x 3" :description "Vertical split")
                        '(:key "C-x o" :description "Go to next window")
                        '(:key "C-x O" :description "Go to previous window")
                        '(:key "C-x C-w" :description "Change window size by arrows")
                        '(:key "M-x untabify" :description "Remove tabs from files")
                        '(:key "M-x recover-file" :description "Recover broken file")
                        '(:key "C-s M-r" :description "Search by regexp")
                        '(:key "C-r M-r" :description "Reverse search by regexp")
                        '(:key "M-%" :description "Query replace inside search")
                        '(:key "C-x SPC" :description "Select rectangle")
                        '(:key "C-t" :description "Transpose symbol with previous one")
                        '(:key "M-t" :description "Transpose word with next one")
                        '(:key "C-M-t" :description "Transpose two balanced S-exps")
                        '(:key "C-x C-t" :description "Transpose two lines")
                        '(:key "C-SPC" :description "Set mark")
                        '(:key "C-u C-SPC" :description "Go to previously saved marks")
                        '(:key "C-x C-SPC" :description "Go to mark from another buffer")
                        '(:key "C-x C-x" :description "Exchange cursor position and the last mark")
                        '(:key "F12" :description "Start LanguageTool check")
                        '(:key "Scroll Lock" :description "Toggle readonly mode in buffer")
                        '(:key "C-x p f" :description "Find file in project")
                        '(:key "C-x p g" :description "Grep in project")
                        '(:key "C-x p D" :description "Open Dired for project")
                        '(:key "C-x p k" :description "Kill all project buffers")
                        '(:key "C-x p c" :description "Compile project")
                        '(:key "C-x p x" :description "Run M-x command in project")
                        '(:key "M-&" :description "Run asynchronous shell command")
                        '(:key "C-x r l" :description "List bookmarks")
                        '(:key "C-x r m" :description "Set bookmark")
                        '(:key "C-x r m bookmark" :description "Set bookmark named bookmark")
                        '(:key "C-x r b bookmark" :description "Jump to bookmark named bookmark")
                        '(:key "M-x bookmark-save" :description "Save current bookmarks to file")
                        '(:key "C-x r SPC" :description "Save position and buffer to register")
                        '(:key "C-x r j" :description "Jump to position from register")
                        '(:key "C-x r s" :description "Save text to register")
                        '(:key "C-x r i" :description "Insert text from register")
                        '(:key "C-x 5 2" :description "Create new frame")
                        '(:key "C-x 5 b" :description "Open buffer in another frame")
                        '(:key "C-x 5 f" :description "Open file in another frame")
                        '(:key "C-x 5 d" :description "Open Dired in another frame")
                        '(:key "C-x 5 0" :description "Destroy current frame")
                        '(:key "C-x +" :description "Balance windows")
                        '(:key "C-M-:" :description "Open IELM")
                        '(:key "M-x re-builder" :description "Build regexp")
                        '(:key "C-M-x" :description "Eval top level S-exp")
                        '(:key "C-h k" :description "Describe keybinding")
                        '(:key "C-h f" :description "Describe function")
                        '(:key "C-h v" :description "Describe variable")
                        '(:key "C-h b" :description "Describe keybindings for current buffer")
                        '(:key "C-M-u" :description "Go to the upper S-exp")
                        '(:key "C-M-b" :description "Go to the start of S-exp")
                        '(:key "C-M-f" :description "Go to the end of S-exp")
                        '(:key "M-r" :description "Replace parent node by the current node")
                        '(:key "C-M-SPC" :description "Select the whole S-exp")
                        '(:key "M-J" :description "Join 2 S-exps")
                        '(:key "M-?" :description "Convolute S-exp")
                        '(:key "M-x checkdoc" :description "Validate documentation of elisp code"))
  (cheatsheet-add-group 'Calendar
                        '(:key "c" :description "Open OrgMode agenda for selected date")
                        '(:key "M-=" :description "Count of days in selected region"))
  (cheatsheet-add-group 'EAT
                        '(:key "C-u M-x eat" :description "Open another instance of EAT")
                        '(:key "C-q" :description "Enter special key in semichar mode")
                        '(:key "C-c M-d" :description "Go to char mode")
                        '(:key "M-RET" :description "Return to semichar mode from char mode")
                        '(:key "C-c C-e" :description "Go to emacs mode")
                        '(:key "C-c C-j" :description "Return to semichar mode from emacs mode")
                        '(:key "C-c C-p" :description "Prompt for password")
                        '(:key "M-x cheatsheet-show" :description "Show cheatsheet")
                        '(:key "C-q" :description "Close cheatsheet"))
  (add-to-list 'display-buffer-alist
               `("^\\*cheatsheet"
                 (display-buffer-in-side-window)
                 (side . bottom)
                 (slot . 0)
                 (window-height . 0.33)
                 (window-parameters (no-delete-other-windows . t))))
  :custom-face
  (cheatsheet-group-face ((t :foreground "blue")))
  (cheatsheet-key-face ((t :foreground "red"))))
